name: ModReqCC
version: ${project.version}
authors: [Nicholas Harris (ScarabCoder)]
main: net.clownercraft.modreqcc.ModReqCC
commands:
  modreq:
    description: Create a new ticket.
    aliases: [report]
  check:
    description: Check status of specific ticket.
  status:
    description: Get status of your currently open tickets.
  ticket:
    description: Modify a specific ticket.